### ISSUE TITLE
Error building: fbjs colliding with itself?

### ISSUE THREAD

**Issue by tomprogers** [facebook/fbjs#116]
I get this error when I try to build my react-native project:

```
Failed to build DependencyGraph: Naming collision detected: /Users/tom/projects/myapp/node_modules/fbjs/flow/include/CSSCore.js collides with /Users/tom/projects/myapp/node_modules/fbjs/lib/CSSCore.js
Error: Naming collision detected: /Users/tom/projects/myapp/node_modules/fbjs/flow/include/CSSCore.js collides with /Users/tom/projects/myapp/node_modules/fbjs/lib/CSSCore.js
    at HasteMap._updateHasteMap (HasteMap.js:132:13)
    at HasteMap.js:103:28
    at tryCallOne (/Users/tom/projects/myapp/node_modules/promise/lib/core.js:37:12)
    at /Users/tom/projects/myapp/node_modules/promise/lib/core.js:123:15
    at flush (/Users/tom/projects/myapp/node_modules/asap/raw.js:50:29)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

If I'm reading this correctly, it says that fbjs is colliding with itself.

**Comment by zpao** [comment]
We stopped shipping the JS for flow and do it differently now so this should be fine.
