### ISSUE TITLE
v0.8.10 patch breaking Enzyme tests

### ISSUE THREAD

**Issue by majapw** [facebook/fbjs#225]
Specifically, `setState` seems unusable in tests after this. I have multiple repos, internal and external (https://travis-ci.org/airbnb/react-dates/jobs/213257781), breaking on this.

The specific error I'm seeing is:
```
ReferenceError: document is not defined
      at getActiveElement (node_modules/fbjs/lib/getActiveElement.js:27:16)
      at ReactReconcileTransaction.getSelectionInformation (node_modules/react-dom/lib/ReactInputSelection.js:37:23)
      at ReactReconcileTransaction.initializeAll (node_modules/react-dom/lib/Transaction.js:172:75)
      at ReactReconcileTransaction.perform (node_modules/react-dom/lib/Transaction.js:139:12)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/Transaction.js:140:20)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/ReactUpdates.js:89:32)
      at Object.flushBatchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:172:19)
      at ReactDefaultBatchingStrategyTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:206:25)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:153:16)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.enqueueUpdate (node_modules/react-dom/lib/ReactUpdates.js:200:22)
      at enqueueUpdate (node_modules/react-dom/lib/ReactUpdateQueue.js:24:16)
      at Object.enqueueSetState (node_modules/react-dom/lib/ReactUpdateQueue.js:209:5)
      at CalendarMonthGrid.ReactComponent.setState (node_modules/react/lib/ReactComponent.js:63:16)
      at CalendarMonthGrid.componentWillReceiveProps (src/components/CalendarMonthGrid.jsx:113:10)
      at Context.<anonymous> (test/components/CalendarMonthGrid_spec.jsx:60:24)
```

@lelandrichardson

**Comment by lencioni** [comment]
For convenience, you can view the diff of 0.8.9 -> 0.8.10 here: https://github.com/facebook/fbjs/compare/d7b0358711f34ae9faa1b5a361da3d0dc1f2af1e...f705a3b8b9dbde366d3e08773e585aec68d1e8e8

**Comment by lelandrichardson** [comment]
Looks like it is this line: https://github.com/facebook/fbjs/compare/d7b0358711f34ae9faa1b5a361da3d0dc1f2af1e...f705a3b8b9dbde366d3e08773e585aec68d1e8e8#diff-8cf49151096a2bcb49d96a0865ccbd02R26

Using `global.document` instead of `document` would fix it I think.

**Comment by lencioni** [comment]
@lelandrichardson yes, I came to the same conclusion

**Comment by lencioni** [comment]
I'll prepare a PR

**Comment by twobitfool** [comment]
I think this fix might have introduced a bug. See #227.
