### ISSUE TITLE
Build failure on clean checkout

### ISSUE THREAD

**Issue by darknoon** [facebook/fbjs#231]
I wanted to contribute to this project but ran into this issue getting started: there is a failing build somewhere when I `npm install` in the appropriate directory (invoked by script `fbjs:test`).

I also tried it with yarn and the latest npm version, but it was still broken.

````
~/Code/OSS/fbjs (master u=) $ npm run fbjs:test

> fbjs-build@ fbjs:test /Users/andrew/Code/OSS/fbjs
> cd packages/fbjs && npm install && npm run test

npm WARN prepublish-on-install As of npm@5, `prepublish` scripts will run only for `npm publish`.
npm WARN prepublish-on-install (In npm@4 and previous versions, it also runs for `npm install`.)
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> fbjs@0.9.0-alpha.2 prepublish /Users/andrew/Code/OSS/fbjs/packages/fbjs
> npm run build


> fbjs@0.9.0-alpha.2 build /Users/andrew/Code/OSS/fbjs/packages/fbjs
> gulp build

[18:49:26] Using gulpfile ~/Code/OSS/fbjs/packages/fbjs/gulpfile.js
[18:49:26] Starting 'build'...
[18:49:26] Starting 'check-dependencies'...
[18:49:29] 'check-dependencies' errored after 2.71 s
[18:49:29] Error in plugin 'check-dependencies'
Message:
    npm broke
[18:49:29] 'build' errored after 2.72 s
[18:49:29] Error in plugin 'run-sequence(check-dependencies)'
Error
    at finish (/Users/andrew/Code/OSS/fbjs/packages/fbjs/node_modules/run-sequence/index.js:56:13)
    at Gulp.onError (/Users/andrew/Code/OSS/fbjs/packages/fbjs/node_modules/run-sequence/index.js:67:4)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:191:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/andrew/Code/OSS/fbjs/packages/fbjs/node_modules/orchestrator/index.js:264:8)
    at /Users/andrew/Code/OSS/fbjs/packages/fbjs/node_modules/orchestrator/index.js:275:23
    at finish (/Users/andrew/Code/OSS/fbjs/packages/fbjs/node_modules/orchestrator/lib/runTask.js:21:8)
    at DestroyableTransform.<anonymous> (/Users/andrew/Code/OSS/fbjs/packages/fbjs/node_modules/orchestrator/lib/runTask.js:52:4)
    at DestroyableTransform.f (/Users/andrew/Code/OSS/fbjs/packages/fbjs/node_modules/end-of-stream/node_modules/once/once.js:17:25)
    at emitOne (events.js:101:20)

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "build"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fbjs@0.9.0-alpha.2 build: `gulp build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fbjs@0.9.0-alpha.2 build script 'gulp build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fbjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fbjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fbjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrew/.npm/_logs/2017-04-11T01_49_29_549Z-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fbjs@0.9.0-alpha.2 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fbjs@0.9.0-alpha.2 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fbjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fbjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fbjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrew/.npm/_logs/2017-04-11T01_49_29_599Z-debug.log

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/Cellar/node/7.8.0/bin/node" "/usr/local/bin/npm" "run" "fbjs:test"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fbjs-build@ fbjs:test: `cd packages/fbjs && npm install && npm run test`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fbjs-build@ fbjs:test script 'cd packages/fbjs && npm install && npm run test'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fbjs-build package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cd packages/fbjs && npm install && npm run test
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fbjs-build
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fbjs-build
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/andrew/.npm/_logs/2017-04-11T01_49_29_655Z-debug.log
````
```
$ npm -v
4.2.0
```

I also tried upgrading to the latest npm:

```
~/Code/OSS/fbjs (master u=) $ npm outdated -g
Package  Current  Wanted  Latest  Location
npm        4.2.0   4.5.0   4.4.4
~/Code/OSS/fbjs (master u=) $ npm install npm@latest -g
```

**Comment by zpao** [comment]
I have some in-progress work to switch over to a better setup that is less fragile, using lerna and yarn. Hopefully that will resolve this when I get a chance to finish it since I'll be updating a bunch of deps all at once.

**Comment by darknoon** [comment]
@zpao is there any workaround so I can get the project building? Want to contribute to this project!

**Comment by zpao** [comment]
You might be able to use node 6 or 4. I saw one  person having an issue
with something in here using node 7, which it looks like you're using too.

Contributing here can be a hit tricky since this doesn't get a ton of
attention and has some interesting syncing dependencies. I won't discourage
it and I'll try to keep an eye out as best I can 😀

**Comment by zpao** [comment]
FYI, this will get fixed in the next day or so by #242 or #244, whichever we decide is better.
