### ISSUE TITLE
self is not defined on server

### ISSUE THREAD

**Issue by clintonwoo** [facebook/fbjs#47]
In my react-relay project I had to change 'self' variables in the following files to 'global' to get the Node server to run... I couldn't run a server using Relay without the change.

/react-relay/node_modules/fbjs/lib/fetch.js
/react-relay/node_modules/fbjs/node_modules/whatwg-fetch/fetch.js

Error given was:
ReferenceError: self is not defined
[1]     at /node_modules/react-relay/node_modules/fbjs/node_modules/whatwg-fetch/fetch.js:4:7
[1]     at Object.<anonymous> (/node_modules/react-relay/node_modules/fbjs/node_modules/whatwg-fetch/fetch.js:330:3)
[1]     at Module._compile (module.js:460:26)
[1]     at Module._extensions..js (module.js:478:10)
[1]     at Object.require.extensions.(anonymous function) [as .js] (/node_modules/babel-core/lib/api/register/node.js:214:7)
[1]     at Module.load (module.js:355:32)
[1]     at Module._load (module.js:310:12)
[1]     at Function.module._load (/node_modules/piping/lib/launcher.js:32:16)
[1]     at Module.require (module.js:365:17)
[1]     at require (module.js:384:17)

**Comment by zpao** [comment]
cc @steveluscher who I think I can at least partially blame for this :stuck_out_tongue_winking_eye: 

I thought we weren't going to get into a situation where `fetch` was actually used in node?

**Comment by steveluscher** [comment]
Hi @clintonwoo. Are you trying to execute a Relay app on the server side in Node? If you are, and you're using the [default network layer that imports fetch](https://github.com/facebook/relay/blob/8106af34c1e15dd35d05aaef48b57becf2beb53a/src/network-layer/default/RelayDefaultNetworkLayer.js#L20), it will break.

github/fetch is [meant to be a browser polyfill only](https://github.com/github/fetch/issues/184#issuecomment-126523046) and they have no plans to make it universal.

What you should likely do, is to create (and inject) a network layer specific for the server side. Since you're already on the server, you might not even have to make network calls – you might choose to craft a network layer that resolves your queries in-place. See the [Network Layer guide](https://facebook.github.io/relay/docs/guides-network-layer.html#custom-network-layers) for more information.

Let's close this issue here. If you want to continue the conversation about your server-side Relay use-case, please do open an issue on the [Relay issue tracker](https://github.com/facebook/relay/issues)!

See also: https://github.com/facebook/fbjs/commit/675d80a71431e5990427357c95454f49242cedd0#commitcomment-12454443
